name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04              # ⬅️ Ubuntu 22.04 en lugar de latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Instalar Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias del sistema
      run: |
        sudo apt update
        sudo apt install -y zip unzip git openjdk-17-jdk wget \
          python3-pip autoconf libtool libtool-bin automake autopoint \
          pkg-config zlib1g-dev libncurses-dev cmake \
          libffi-dev libssl-dev

    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Aceptar licencias Android
      run: yes | sdkmanager --licenses

    - name: Instalar Build Tools 34
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-34"
        sdkmanager "build-tools;34.0.0"

    - name: Compilar APK
      env:
        ANDROIDSDK: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      run: |
        buildozer android debug

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
